name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings || true

    - name: Generate last test attempt report
      if: ${{failure()}}
      run: |
        pytest --maxfail=1 --disable-warnings > last_test_attempt_report.txt || true
        cat last_test_attempt_report.txt

    - name: Commit and push test report
      if: ${{failure()}}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add last_test_attempt_report.txt
        git commit -m "Add last test attempt report"
        git push
